settings:
  title: 'Status Page'
  url: 'https://status-production.chinatelecom.workers.dev' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: '所以站点运行正常'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: piximg # unique identifier
    name: piximg proxy
    description: 'piximg proxy.' # default=empty
    url: 'https://piximg.20140301.xyz' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: true # allows the title to be a link, default=true

  - id: why not baidu
    name: why not baidu
    description: 'ipv6 only,redirect to baidu search.'
    url: 'https://web.20140301.xyz'
    method: GET
    expectStatus: 200
    linkable: true # allows the title to be a link, default=true

  - id: whoogle
    name: whoogle search
    description: 'whoogle search.'
    url: 'https://20150412.xyz'
    method: GET
    expectStatus: 200
    linkable: true # allows the title to be a link, default=true
  - id: ip
    name: ip address
    description: 'get your public ip address over cloudflare.'
    url: 'https://ip.20140301.xyz/'
    method: GET
    expectStatus: 200
    
  - id: cloudflare dns
    name: cloudflare dns
    description: 'cloudflare dns over https.'
    url: 'https://cloudflare-dns.com/dns/'
    method: GET
    expectStatus: 200
